tutorialportal/admins/student_manager/forms.py
from flask_wtf import FlaskForm
from wtforms import DateField, StringField, FloatField, TextAreaField, SubmitField
from wtforms.validators import DataRequired, Length, ValidationError

import datetime
import re


class AddStudentForm(FlaskForm):
    name = StringField('Student Name', validators=[DataRequired(), Length(max=50)])
    s_phone = StringField('Student\'s phone')
    p_phone = StringField('Parent\'s phone')
    p_rel = StringField('Parent-Child Relationship', validators=[Length(max=20)])
    lesson_day = StringField('Day(s) of lessons', validators=[DataRequired(), Length(min=3, max=30)])
    lesson_time = StringField('Start time of Lessons', validators=[DataRequired()])
    lesson_duration = FloatField('Duration of lessons (hours)', validators=[DataRequired()])
    lesson_fee = FloatField('Charge per lesson', validators=[DataRequired()])
    remarks = TextAreaField('Remarks', render_kw={"rows": 1})
    add_student_submit = SubmitField('Submit')

    def validate_name(self, name):
        if not re.search('[\w]+[ ][\w]+[\w ]*', name.data):
            raise ValidationError('Invalid name!')

    def validate_lesson_day(self, lesson_day):
        if not re.search('^([A-Z][a-z]{2,3})([,][A-Z][a-z]{2,3}){0,6}$', lesson_day.data):
            raise ValidationError('Invalid day(s)!  E.g., \'Tue,Thur\'')

    def validate_lesson_time(self, lesson_time):
        if not re.search('^\d{2}:\d{2}$', lesson_time.data):
            raise ValidationError('Invalid lesson start time. Must be XX:XX, e.g., 13:30')

    def validate_s_phone(self, s_phone):
        if not re.search('^[5679]\d{7}$', s_phone.data) and not s_phone.data == '':
            raise ValidationError('Field must be an 8-digit HK phone number.')

    def validate_p_phone(self, p_phone):
        if not re.search('^[5679]\d{7}$', p_phone.data) and not p_phone.data == '':
            raise ValidationError('Field must be an 8-digit HK phone number.')


class AStudentCredentialsForm(FlaskForm):
    name = StringField('Student Name', validators=[DataRequired(), Length(max=50)])
    s_phone = StringField('Student\'s phone')
    p_phone = StringField('Parent\'s phone')
    p_rel = StringField('Parent-Child Relationship', validators=[Length(max=20)])
    lesson_day = StringField('Day(s) of lessons', validators=[DataRequired(), Length(min=3, max=30)])
    lesson_time = StringField('Start time of Lessons', validators=[DataRequired()])
    lesson_duration = FloatField('Duration of lessons (hours)', validators=[DataRequired()])
    lesson_fee = FloatField('Charge per lesson', validators=[DataRequired()])
    remarks = TextAreaField('Remarks', render_kw={"rows": 1})
    a_student_credentials_submit = SubmitField('Save Changes')

    def validate_name(self, name):
        if not re.search('[\w]+[ ][\w]+[\w ]*', name.data):
            raise ValidationError('Invalid name!')

    def validate_lesson_day(self, lesson_day):
        if not re.search('^([A-Z][a-z]{2,3})([,][A-Z][a-z]{2,3}){0,6}$', lesson_day.data):
            raise ValidationError('Invalid day(s)!  E.g., \'Tue,Thur\'')

    def validate_lesson_time(self, lesson_time):
        if not re.search('^[012]\d:[0-5]\d$', lesson_time.data):
            raise ValidationError('Invalid lesson start time. Must be XX:XX, e.g., 13:30')

    def validate_s_phone(self, s_phone):
        if not re.search('^[5679]\d{7}$', s_phone.data) and not s_phone.data == '':
            raise ValidationError('Field must be an 8-digit HK phone number.')

    def validate_p_phone(self, p_phone):
        if not re.search('^[5679]\d{7}$', p_phone.data) and not p_phone.data == '':
            raise ValidationError('Field must be an 8-digit HK phone number.')


class AddAttendanceForm(FlaskForm):
    lesson_date = DateField('Date', default=datetime.datetime.now().date(), format='%Y-%m-%d',
                            validators=[DataRequired(message='Invalid date. (YYYY-MM-DD)')])
    lesson_time = StringField('Time', validators=[DataRequired()])
    lesson_duration = StringField('Duration (hrs)', validators=[DataRequired()])
    lesson_fee = FloatField('Charge ($)', validators=[DataRequired()])
    remarks = TextAreaField('Remarks', render_kw={"rows": 1})
    add_attendance_submit = SubmitField('Submit')

    def validate_lesson_time(self, lesson_time):
        if not re.search('^[012]\d:[0-5]\d$', lesson_time.data):
            raise ValidationError('Invalid lesson time. Must be XX:XX, e.g., 13:30')

tutorialportal/admins/info/routes.py
from flask import Blueprint, render_template
from flask_login import login_required

from tutorialportal.config_test import site

admins_info = Blueprint('admins_info', __name__)


@admins_info.route('/info')
@login_required
def info():
    return render_template('admins/info.html', page_name='Information', site=site)

tutorialportal/tutors/info/routes.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user

from tutorialportal.config import site_en
from tutorialportal.tutors.info.utils import generate_calender, generate_chart

tutors_info = Blueprint('tutors_info', __name__)


@tutors_info.route('/info')
@login_required
def info():
    calendar = generate_calender(current_user.username)
    monthly_income_chart = {
        24: generate_chart(current_user.username, 24),
        12: generate_chart(current_user.username, 12),
        9: generate_chart(current_user.username, 9),
        6: generate_chart(current_user.username, 6)
    }
    return render_template('tutors/info.html', page_name='Information', site=site_en, calendar=calendar,
                           monthly_income_chart=monthly_income_chart)

tutorialportal/tutors/student_manager/routes.py
from flask import Blueprint, abort, flash, request, redirect, render_template, url_for
from flask_login import current_user, login_required

from tutorialportal import db, bcrypt
from tutorialportal.tutors.student_manager.forms import AddStudentForm, StudentCredentialsForm, AddAttendanceForm, \
    AddPaymentForm
from tutorialportal.models import Student, User, Attendance, FeeSubmission
from tutorialportal.config import site_en
from tutorialportal.tutors.student_manager.utils import get_highlight_count, get_all_invoice_items, day_dictionary, \
    convert_days, day_list

import datetime
import random

tutors_student_manager = Blueprint('tutors_student_manager', __name__)


@tutors_student_manager.route('/manager/student', methods=['POST', 'GET'])
@tutors_student_manager.route('/manager/student_<string:page>', methods=['POST', 'GET'])
@login_required
def student_manager(page=None):
    if current_user.tutor is False:
        abort(403)
    active_students = [(student_record.username, student_record.name) for student_record in
                       Student.query.filter_by(tutor_username=current_user.username) if student_record.active]
    inactive_students = [(student_record.username, student_record.name) for student_record in
                         Student.query.filter_by(tutor_username=current_user.username) if not student_record.active]
    add_student_form = AddStudentForm()
    panel_active = {
        'add_student': False,
        'select_student': False
    }
    if page and page in panel_active.keys():
        panel_active[page] = True
    if request.method == 'GET' and page is None:
        panel_active['select_student'] = True
    if add_student_form.add_student_submit.data:
        if add_student_form.validate_on_submit():
            username = add_student_form.name.data.split(" ")[0].lower() + datetime.datetime.now().strftime('%S%M%H')
            while User.query.get(username) is not None:
                username = add_student_form.name.data.split(" ")[0].lower() + datetime.datetime.now().strftime('%S%M%H')
            password = add_student_form.name.data.replace(" ", "") + str(random.randint(10, 100))
            user = User(username=username, password=bcrypt.generate_password_hash(password).decode('utf-8'),
                        tutor=False)
            db.session.add(user)
            input_lesson_time = add_student_form.lesson_time.data
            student = Student(username=username, name=add_student_form.name.data, s_phone=add_student_form.s_phone.data,
                              p_phone=add_student_form.p_phone.data, p_rel=add_student_form.p_rel.data,
                              lesson_day=','.join(convert_days(add_student_form.lesson_day.data)),
                              lesson_time=input_lesson_time if len(
                                  input_lesson_time) == 5 else \
                                  input_lesson_time[:2] + ':' + input_lesson_time[2:] \
                                      if ':' not in input_lesson_time else '0' + input_lesson_time
                              , lesson_duration=add_student_form.lesson_duration.data,
                              lesson_fee=add_student_form.lesson_fee.data, remark=add_student_form.remarks.data,
                              tutor_username=current_user.username, active=True)
            db.session.add(student)
            db.session.commit()
            flash('ADD Success: Student \nUsername: {}\nPassword: {}'.format(username, password), 'success')
            return redirect(url_for('tutors_student_manager.student_manager', student_username=username))
        if page is None:
            panel_active['add_student'] = True
    return render_template('tutors/student_manager.html', page_name='Student Manager',
                           add_student_form=add_student_form,
                           site=site_en, panel_active=panel_active, active_students=active_students,
                           inactive_students=inactive_students)


@tutors_student_manager.route('/manager/student/<string:student_username>', methods=['POST', 'GET'])
@tutors_student_manager.route('/manager/student/<string:student_username>/<string:page>', methods=['POST', 'GET'])
@login_required
def student_manager_selected(student_username, page=None):
    if current_user.tutor is False:
        abort(403)
    # Credentials Form, Add Attendance Form,
    # Add Payment Form, Attendance Table with controls, Payment History with controls
    panel_active = {
        'credentials': False,
        'attendance': False,
        'payment': False
    }
    if page and page in panel_active.keys():
        panel_active[page] = True
    student = Student.query.filter_by(username=student_username).first_or_404()
    if student.tutor_username != current_user.username:
        abort(403)
    if request.method == 'GET' and page is None:
        if student.active is False:
            panel_active['credentials'] = True
        else:
            panel_active['attendance'] = True
    student_credentials_form = StudentCredentialsForm()
    add_attendance_form = AddAttendanceForm()
    add_payment_form = AddPaymentForm()
    if student_credentials_form.student_credentials_submit.data:
        if student_credentials_form.validate_on_submit():
            student.name = student_credentials_form.name.data
            student.s_phone = student_credentials_form.s_phone.data
            student.p_phone = student_credentials_form.p_phone.data
            student.p_rel = student_credentials_form.p_rel.data
            student.lesson_day = ','.join(convert_days(student_credentials_form.lesson_day.data))
            input_lesson_time = student_credentials_form.lesson_time.data
            student.lesson_time = input_lesson_time if len(
                input_lesson_time) == 5 else \
                input_lesson_time[:2] + ':' + input_lesson_time[2:] \
                    if ':' not in input_lesson_time else '0' + input_lesson_time
            student.lesson_duration = student_credentials_form.lesson_duration.data
            student.lesson_fee = student_credentials_form.lesson_fee.data
            student.remark = student_credentials_form.remarks.data
            db.session.commit()
            flash('UPDATE Success: Credentials ({}).'.format(student.name), 'success')
        else:
            flash('Some of your input may be invalid.', 'danger')
        if page is None:
            panel_active['credentials'] = True
    elif add_attendance_form.add_attendance_submit.data:
        if add_attendance_form.validate_on_submit():
            # Possibly add a check in timeslot overlapping
            input_lesson_time = add_attendance_form.lesson_time.data
            attendance = Attendance(username=student.username, lesson_date=add_attendance_form.lesson_date.data,
                                    lesson_time=input_lesson_time if len(
                                        input_lesson_time) == 5 else input_lesson_time[:2] + ':' + input_lesson_time[2:]
                                    if ':' not in input_lesson_time else '0' + input_lesson_time,
                                    lesson_fee=add_attendance_form.lesson_fee.data,
                                    lesson_duration=add_attendance_form.lesson_duration.data,
                                    remark=add_attendance_form.remarks.data)
            db.session.add(attendance)
            db.session.commit()
            flash('ADD Success: Attendance ({} {}) added for {}.'.format(add_attendance_form.lesson_date.data,
                                                                         add_attendance_form.lesson_time.data,
                                                                         student.name),
                  'success')
        else:
            flash('Some of your input may be invalid.', 'danger')
        panel_active['attendance'] = True
    elif add_payment_form.add_payment_submit.data:
        if add_payment_form.validate_on_submit():
            payment = FeeSubmission(username=student_username, submission_date=add_payment_form.submission_date.data,
                                    amount=add_payment_form.amount.data, remark=add_payment_form.remarks.data)
            db.session.add(payment)
            db.session.commit()
            flash('ADD Success: Payment ({} ${}) added for {}.'.format(add_payment_form.submission_date.data,
                                                                       add_payment_form.amount.data,
                                                                       student.name),
                  'success')
        else:
            flash('Some of your input may be invalid.', 'danger')
        panel_active['payment'] = True
    student_credentials_form.name.data = student.name
    student_credentials_form.s_phone.data = student.s_phone
    student_credentials_form.p_phone.data = student.p_phone
    student_credentials_form.p_rel.data = student.p_rel
    student_credentials_form.lesson_day.data = ','.join([day_list[int(i)] for i in student.lesson_day.split(',')])
    student_credentials_form.lesson_time.data = student.lesson_time
    student_credentials_form.lesson_duration.data = student.lesson_duration
    student_credentials_form.lesson_fee.data = student.lesson_fee
    student_credentials_form.remarks.data = student.remark
    add_attendance_form.lesson_time.data = student.lesson_time
    add_attendance_form.lesson_duration.data = student.lesson_duration
    add_attendance_form.lesson_fee.data = student.lesson_fee
    add_payment_form.amount.data = student.lesson_fee
    # Student Attendance Record
    page_num_a = request.args.get('ap', 1, type=int)
    page_num_p = request.args.get('pp', 1, type=int)
    student_attendance = Attendance.query.filter_by(username=student.username).order_by(
        Attendance.lesson_date.desc()).paginate(page=page_num_a, per_page=5)
    student_payment = FeeSubmission.query.filter_by(username=student.username).order_by(

tutorialportal/templates/tutors/info.html
{% extends "layout.html" %}
{% block content %}
    <div class="accordion" id="InfoBodyAccordion">
        <div class="accordion-item">
            <h2 class="accordion-header" id="headingOne">
                <button class="accordion-button" type="button" data-bs-toggle="collapse"
                        data-bs-target="#CredentialsCollapse"
                        aria-expanded="true" aria-controls="CredentialsCollapse">
                    <h4>Your Credentials</h4>
                </button>
            </h2>
            <div id="CredentialsCollapse" class="accordion-collapse collapse show" aria-labelledby="headingOne"
                 data-bs-parent="#InfoBodyAccordion">
                <div class="accordion-body">

                </div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header" id="headingTwo">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#CalendarCollapse" aria-expanded="false" aria-controls="CalendarCollapse">
                    <h4>Weekly Tutorial Schedule</h4>
                </button>
            </h2>
            <div id="CalendarCollapse" class="accordion-collapse collapse" aria-labelledby="headingTwo"
                 data-bs-parent="#InfoBodyAccordion">
                <div class="accordion-body">
                    <div class="table-responsive">
                        <table class="table table-bordered caption-top align-middle" style="text-align: center">
                            <caption>Calendar-view of your weekly schedule (30 mins/slot)</caption>
                            <thead class="table-dark">
                            {% for day in range(8) %}
                                <th scope="col">{{ calendar[0][day] }}</th>
                            {% endfor %}
                            </thead>
                            <tbody>
                            {% for row in range(1, calendar|length) %}
                                {% if calendar[row][1:8] != ['', '', '', '', '', '', ''] %}
                                    <tr>
                                        <th scope="row">{{ calendar[row][0] }}</th>
                                        {% for column in range(1, 8) %}
                                            <td style="white-space: nowrap">{{ calendar[row][column] }}</td>
                                        {% endfor %}
                                    </tr>
                                {% endif %}
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header" id="headingThree">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#InsightsCollapse" aria-expanded="false" aria-controls="InsightsCollapse">
                    <h4>Insights and Analytics</h4>
                </button>
            </h2>
            <div id="InsightsCollapse" class="accordion-collapse collapse" aria-labelledby="headingThree"
                 data-bs-parent="#InfoBodyAccordion">
                <div class="accordion-body overflow-auto text-center">
                    <figure class="figure">
                        <img src='data:image/png;base64,{{ monthly_income_chart.get(9) }}'
                             alt="Monthly Income Chart"/>
                        <figcaption class="figure-caption">You can interpret "By Attendance Record" as the
                            expected salary you should receive in the month and "By Payment Record" as the amount that
                            you actually received.
                        </figcaption>
                    </figure>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

tutorialportal/templates/tutors/student_manager.html
{% extends "layout.html" %}
{% block content %}
    <div>
        {% with messages = get_flashed_messages(with_categories=true, category_filter=['danger', 'success']) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}" style="padding-top: 9px">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        <h3 class="text-center">Student Manager</h3>
    </div>
    <div class="container d-flex flex-wrap">
        {% set panel_buttons = ["Select Student", "Add Student"] %}
        {% for button in panel_buttons %}
            <button class="btn btn-dark flex-fill col-md-4" type="button" data-bs-toggle="collapse"
                    data-bs-target="#{{ button.split(" ")|join("") }}Button"
                    aria-expanded="false" aria-controls="{{ button.split(" ")|join("") }}Button" style="margin: 3px">
                {{ button }}
            </button>
        {% endfor %}
    </div>
    <div>
        {% set show_select_student = '' %}
        {% if panel_active.get('select_student') %}
            {% set show_select_student = ' show' %}
        {% endif %}
        <div class="SelectStudentButton collapse multi-collapse in{{ show_select_student }}" id="SelectStudentButton">
            <div class="card card-body">
                <h4 class="border-bottom mb-2 h4">Active Students</h4>
                <div>
                    {% if active_students|count == 0 %}
                        <button class="btn btn-outline-secondary col-auto" type="button" data-bs-toggle="collapse"
                                data-bs-target="#AddStudentButton"
                                aria-expanded="false" aria-controls="AddStudentButton"
                                style="min-width: 150px; margin-bottom: 5px">
                            Nothing to show. Add more students.
                        </button>
                    {% endif %}
                    {% for username, name in active_students %}
                        <a href="{{ url_for('tutors_student_manager.student_manager_selected', student_username=username) }}"
                           class="btn btn-outline-success col-auto"
                           style="min-width: 150px; margin-bottom: 5px">{{ name }}</a>
                    {% endfor %}
                </div>
                <h4 class="border-bottom mb-2 h4" style="margin-top: 5px">Inactive Students</h4>
                <div>
                    {% for username, name in inactive_students %}
                        <a href="{{ url_for('tutors_student_manager.student_manager_selected', student_username=username) }}"
                           class="btn btn-outline-danger col-auto"
                           style="min-width: 150px; margin-bottom: 5px">{{ name }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% set show_add_student = '' %}
        {% if panel_active.get('add_student') %}
            {% set show_add_student = ' show' %}
        {% endif %}
        <div class="AddStudentButton collapse multi-collapse in{{ show_add_student }}" id="AddStudentButton">
            <div class="card card-body">
                <h4 class="border-bottom mb-2 h4">Add Student</h4>
                <form method="POST" action="" class="row gy-3 gx-3 align-items-center">
                    {{ add_student_form.hidden_tag() }}
                    {% set form_elements_1 = [add_student_form.name, add_student_form.s_phone, add_student_form.p_phone] %}
                    {% set form_elements_2 = [add_student_form.p_rel, add_student_form.lesson_day, add_student_form.lesson_time] %}
                    {% set form_elements_3 = [add_student_form.lesson_duration, add_student_form.lesson_fee, add_student_form.remarks] %}
                    {% for element in form_elements_1 + form_elements_2 + form_elements_3 %}
                        <div class="form-group col-md-4">
                            {{ element.label(class="form-control-label") }}
                            {% if element.errors %}
                                {{ element(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in element.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ element(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                    {% endfor %}
                    <div class="form-group" style="padding-top: 5px">
                        {{ add_student_form.add_student_submit(class="btn btn-dark") }}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}