tutorialportal/main/routes.py
from flask import Blueprint, request, redirect, url_for, render_template, flash
from flask_login import current_user, login_user, logout_user, login_required

from tutorialportal.main.forms import LoginForm, RegistrationForm
from tutorialportal.models import User, Tutor
from tutorialportal.config import site_en
from tutorialportal import bcrypt, db

import random

main = Blueprint('main', __name__)


@main.route('/login', methods=['POST', 'GET'])
def login():
    show_intro = request.method == 'GET'
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        user_not_found = False
        dummy = bcrypt.generate_password_hash(form.password.data + str(random.random())).decode('utf-8')
        if user is None:
            user_not_found = True
        if bcrypt.check_password_hash(user.password if not user_not_found else dummy, form.password.data):
            login_user(user)
            next_page = request.args.get('next')
            return redirect(next_page if next_page else url_for('main.home'))
        flash('* Incorrect username or password', 'danger')
    return render_template('general/login.html', page_name='Login', form=form, site=site_en, show_intro=show_intro)


@main.route('/register', methods=['POST', 'GET'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data,
                    password=bcrypt.generate_password_hash(form.password.data).decode('utf-8'), tutor=True)
        db.session.add(user)
        tutor = Tutor(username=form.username.data, name=form.name.data, email=form.email.data)
        db.session.add(tutor)
        db.session.commit()
        flash('* Registration complete. Please log in.', 'success')
        return redirect(url_for('main.login'))
    return render_template('general/register.html', page_name='Register as Tutor', form=form, site=site_en)


@main.route('/logout')
def logout():
    logout_user()
    flash('* You have been logged out.', 'success')
    return redirect(url_for('main.login'))


@main.route('/')
@main.route('/home')
@login_required
def home():
    return render_template('general/home.html', page_name='Home', site=site_en)

tutorialportal/tutors/info/routes.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user

from tutorialportal.config import site_en
from tutorialportal.tutors.info.utils import generate_calender, generate_chart

tutors_info = Blueprint('tutors_info', __name__)


@tutors_info.route('/info')
@login_required
def info():
    calendar = generate_calender(current_user.username)
    monthly_income_chart = {
        24: generate_chart(current_user.username, 24),
        12: generate_chart(current_user.username, 12),
        9: generate_chart(current_user.username, 9),
        6: generate_chart(current_user.username, 6)
    }
    return render_template('tutors/info.html', page_name='Information', site=site_en, calendar=calendar,
                           monthly_income_chart=monthly_income_chart)

tutorialportal/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
            integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{{ url_for('static', filename='panel-toggles.js') }}"></script>
    <title>{{ site.get('name') }} - {{ page_name }}</title>
</head>
<body class="d-flex flex-column min-vh-100">
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-light" style="background-color: #fbefeb; padding-inline: 1.7%">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('main.home') }}">Welcome to {{ site.get('name') }}</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                    aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    {% if current_user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.home') }}">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                Panels
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                                {% if current_user.tutor %}
                                    <li><a class="dropdown-item" href="{{ url_for('tutors_info.info') }}">Information
                                        and Controls</a></li>
                                    <li><a class="dropdown-item"
                                           href="{{ url_for('tutors_student_manager.student_manager') }}">Student
                                        Manager</a></li>
                                {% else %}
                                    <li><a class="dropdown-item" href="#">Credentials</a></li>
                                    <li><a class="dropdown-item" href="#">Attendance Record</a></li>
                                    <li><a class="dropdown-item" href="#">Payment Record</a></li>
                                {% endif %}
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.logout') }}">Logout</a>
                        </li>
                    {% endif %}
                </ul>
                {% if not current_user.is_authenticated %}
                    <span class="navbar-nav nav-item">
                        {% if page_name == 'Login' %}
                            <a class="nav-link" href="{{ url_for('main.register') }}">Register (Tutor)</a>
                        {% else %}
                            <a class="nav-link" href="{{ url_for('main.login') }}">Login</a>
                        {% endif %}
                    </span>
                {% endif %}
            </div>
        </div>
    </nav>
</header>
<main role="main" class="container">
    <div class="row" style="padding-top: 15px">
        {% block content %}{% endblock content %}
    </div>
</main>
<footer class="bg-dark text-white mt-auto" style="padding-inline: 1.5%">
    <small>© 2021 <a class="text-white" style="text-decoration: none" href="https://github.com/gordonmhy/tutorialportal">GORDONMHY</a></small>
</footer>
</body>
</html>